# Site
title:              Microsoft DS Toolkit
bio:                'Microsoft DS Toolkit'
description:        "Microsoft DS Toolkit"
locale:             en_UK
baseurl: "" # the subpath of your site, e.g. 
url: "https://jbetts05.github.io/" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "G-4DLMYEX176"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           UK
phone:              310-318-5555
email:              joshbetts@microsoft.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/toolkit/:title/"
    layout: post
    author:

# Jekyll
permalink:          /toolkit/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/toolkit/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
